name: Auto Merge Other-repo and PR

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  merge_other_repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v3.5.3
      with:
        ref: master
    - name: Add remote repository
      run: git remote add other-repo https://github.com/cwj851/XQuickEnergy.git
    - name: Fetch other repository
      run: git fetch other-repo
    - name: Merge other repository
      run: git merge other-repo/master
    - name: Push changes
      run: git push origin master
  automerge_pr:
    needs: merge_other_repo
    runs-on: ubuntu-latest
    steps:
    - id: automerge
      name: automerge
      uses: "pascalgn/automerge-action@v0.15.6"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_RETRIES: "6"
        MERGE_RETRY_SLEEP: "300000"
