name: Android CI

on:
  workflow_dispatch:

jobs:
  android:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Get versionName and versionCode from build.gradle
        run: |
          VERSION_NAME=$(grep -oP 'versionName "\K(.*?)(?=")' app/build.gradle)
          VERSION_CODE=$(grep -oP 'versionCode \K(\d+)' app/build.gradle)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "TAG_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease --build-cache --parallel --no-daemon --warning-mode all

      - name: Sign app APK
        uses: ilharp/sign-android-release@v1.0.4
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 33.0.0

      - name: Upload Apk to Release Action
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.sign_app.outputs.signedFile }}
          asset_name: xqe-sesame-${{ env.VERSION_NAME }}_${{ env.VERSION_CODE }}.apk
          tag: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          overwrite: true
