name: Android CI

on:
  push:
    branches:
      - master

jobs:
  android:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3.3.1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        id: build
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: ./gradlew assembleRelease --build-cache --parallel --no-daemon --warning-mode all
      - name: Sign app APK
        id: sign
        if: steps.build.outcome == 'success'
        uses: ilharp/sign-android-release@v1.0.4
        with:
          releaseDir: app/build/outputs/apk/release/
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 33.0.0
      - name: Get versionName from build.gradle
        id: version
        run: |
          VERSION_NAME=$(grep -oP 'versionName "\K(.*?)(?=")' app/build.gradle)
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
      - name: Check if tag exists and Set tag name
        id: tag
        run: |
          TAG_EXISTS=$(git ls-remote --tags origin refs/tags/$VERSION_NAME)
          if [ -z "$TAG_EXISTS" ]; then
            echo "TAG_NAME=$VERSION_NAME" >> $GITHUB_ENV
          else
            TIMESTAMP=$(TZ="Asia/Shanghai" date +'%Y-%m-%d_%H-%M-%S')
            echo "TAG_NAME=$TIMESTAMP" >> $GITHUB_ENV
          fi
      - name: Upload Apk to Release Action
        if: steps.sign.outcome == 'success'
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.LONGLONG }}
          file: ${{ steps.sign_app.outputs.signedFile }}
          asset_name: xqe-sesame_longlong-signed-${{ env.TAG_NAME }}.apk
          tag: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          body: ${{ env.LATEST_COMMIT_MESSAGE }}
